SistemaDeGestion/SistemaDeGestion/Models/Request.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public int estado { get; set; }
        public string descripcion { get; set; }
        public string destino { get; set; }
        public string origen { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string rutaFile { get; set; }
    }
}

SistemaDeGestion/SistemaDeGestion/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaDeGestion.Models;

namespace SistemaDeGestion.Controllers
{
    public class RequestController : Controller
    {
        // GET: Request
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int Id)
        {
            if (Id == -1)
            {
                return View();
            }

            DataBasesSGCEntities db = new DataBasesSGCEntities();
            ViewBag.destino = db.Flyer.Find(Id).name;
            return View();
        }

        [HttpPost]
        public ActionResult Create(RequestModel model)
        {

            if(!ModelState.IsValid)
            {
                return View(model);
            }

            return View();
        }
    }
}

SistemaDeGestion/SistemaDeGestion/Views/Request/Create.cshtml
@model SistemaDeGestion.Models.RequestModel

@{
    ViewBag.Title = "Solicitar Cotizacion";
}

<h2>Solicitar Cotización</h2>

<div class="alert alert-warning alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong>¡Cuidado!</strong> 
</div>

<div class="row">
    <div class="col-lg-12">
        @using (Html.BeginForm("Create", "Request", FormMethod.Post))
        {
            @Html.ValidationMessage("Error", new { @class = "text-danger" })

            <div class="col-md-6">
                @Html.LabelFor(model => model.Nombre)
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
                <br />
            </div>
            <div class="col-md-6">
                @Html.LabelFor(model => model.Apellido)
                @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
                @Html.ValidationMessage("Apellido", new { @class = "text-danger" })
                <br />
            </div>
            <div class="col-md-6">
                @Html.LabelFor(model => model.Correo)
                @Html.TextBoxFor(model => model.Correo, new { @class = "form-control" })
                @Html.ValidationMessage("Correo", new { @class = "text-danger" })
                <br />
            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.Telefono)
                @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })
                @Html.ValidationMessage("Telefono", new { @class = "text-danger" })
                <br />
            </div>
            <div class="form-group col-sm-6">

                @Html.LabelFor(model => model.Destino)
                @if (@ViewBag.destino != null)
                {
                    @Html.TextBoxFor(model => model.Destino, new { @class = "form-control", @Value = ViewBag.destino })
                }
                else
                {
                    @Html.TextBoxFor(model => model.Destino, new { @class = "form-control" })

                }
                @Html.ValidationMessage("Destino", new { @class = "text-danger" })

                <br />
            </div>
            <div class="form-group col-sm-6">
                @Html.LabelFor(model => model.Origen)
                @Html.TextBoxFor(model => model.Origen, new { @class = "form-control" })
                @Html.ValidationMessage("Origen", new { @class = "text-danger" })
                <br />
            </div>
            <div class="form-group col-sm-12">
                @Html.LabelFor(model => model.Descripcion)
                @Html.TextAreaFor(model => model.Descripcion, 4, 10, new { style = "width : 100%; max-width : 100%", @class = "form-control" })
                @Html.ValidationMessage("Descripcion", new { @class = "text-danger"})
                <br />
                <br />
            </div>
            <br />
            <br />
            <div>
                <input type="submit" class="btn btn-success" value="Aceptar" />
                <button onclick="document.location.href='@Url.Content("~/Home/Index")'" type="button" class="btn btn-danger">
                    Cancelar
                    <span class="glyphicon glyphicon-remove"></span>
                </button>
            </div>
        }
    </div>
</div>