SistemaDeGestion/SistemaDeGestion/Models/Flyer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaDeGestion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flyer
    {
        public int id { get; set; }
        public string description { get; set; }
        public string imagen { get; set; }
        public string name { get; set; }
    }
}

SistemaDeGestion/SistemaDeGestion/Controllers/FlyerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaDeGestion.Models;
using SistemaDeGestion.Classes;

namespace SistemaDeGestion.Controllers
{
    public class FlyerController : Controller
    {
        // GET: Flyer
        public ActionResult Index()
        {
            List<FlyerModel> lst = null;

            using (DataBasesSGCEntities db = new DataBasesSGCEntities())
            {
                lst = (from d in db.Flyer
                       select new FlyerModel
                       {
                           Id = d.id,
                           Name = d.name,
                           Description = d.description,
                           Imagen = d.imagen
                       }).ToList();
            }

            return View(lst);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(ImageFlyer model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //Verificar si hay una imagen https://www.youtube.com/watch?v=XtjoCuE_J48

            var pic = string.Empty;
            var folder = "~/Content/img";

            if(model.ImageFile == null)
            {
                return View(model);
            }

            pic = FilesHelper.UploadPhoto(model.ImageFile, folder);
            pic = string.Format("{0}/{1}", folder, pic);

            using (var db = new DataBasesSGCEntities())
            {
                Flyer oFlyer = new Flyer();
                oFlyer.description = model.Description;
                oFlyer.name = model.Name;
                oFlyer.imagen = model.Imagen;
                oFlyer.imagen = pic;

                db.Flyer.Add(oFlyer);
                db.SaveChanges();

            }

            return Redirect(Url.Content("~/Flyer/Index"));
        }

        public ActionResult Edit(int Id)
        {
            EditImageFlyer model = new EditImageFlyer();
            
            using (var db = new DataBasesSGCEntities())
            {
                var oFlyer = db.Flyer.Find(Id);
                model.Description = oFlyer.description;
                model.Name = oFlyer.name;
                model.Imagen = oFlyer.imagen;
                model.Id = oFlyer.id;
            }
            
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(EditImageFlyer model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            
            var pic = string.Empty;
            var folder = "~/Content/img";

            if (model.ImageFile != null)
            {
                pic = FilesHelper.UploadPhoto(model.ImageFile, folder);
                pic = string.Format("{0}/{1}", folder, pic);

                using (var db = new DataBasesSGCEntities())
                {
                    var oFlyer = db.Flyer.Find(model.Id);
                    oFlyer.description = model.Description;
                    oFlyer.name = model.Name;
                    oFlyer.imagen = model.Imagen;
                    oFlyer.imagen = pic;

                    db.Entry(oFlyer).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }
            else
            {
                using (var db = new DataBasesSGCEntities())
                {
                    var oFlyer = db.Flyer.Find(model.Id);
                    oFlyer.description = model.Description;
                    oFlyer.name = model.Name;

                    db.Entry(oFlyer).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
            }

            return Redirect(Url.Content("~/Flyer/Index"));
        }

        public ActionResult Delete(int Id)
        {
            DeleteFlyerModel model = new DeleteFlyerModel();

            using (var db = new DataBasesSGCEntities())
            {
                var oFlyer = db.Flyer.Find(Id);

                model.Description = oFlyer.description;
                model.Imagen = oFlyer.imagen;
            }

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(DeleteFlyerModel model)
        {
            using (var db = new DataBasesSGCEntities())
            {
                Flyer oFlyer = db.Flyer.Find(model.Id);
                db.Flyer.Remove(oFlyer);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Flyer/Index"));
        }

    }
}

SistemaDeGestion/SistemaDeGestion/Views/Flyer/Create.cshtml
@model SistemaDeGestion.Models.ImageFlyer

@{
    ViewBag.Title = "Agregar Flyer";
}

<h2>Create</h2>

<div class="row">
    <div class="col-lg-12">

        @using (Html.BeginForm("Create", "Flyer", FormMethod.Post, new { role = "form", @class = "", enctype = "multipart/form-data" }))
        {
            @Html.ValidationMessage("Error", new { @class = "text-danger" })

            @Html.LabelFor(d => d.Name)
            @Html.TextBoxFor(d => d.Name, new { @class = "form-control" })
            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.Description)
            @Html.TextBoxFor(d => d.Description, new { @class = "form-control" })
            @Html.ValidationMessage("Description", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.ImageFile)
            @Html.TextBoxFor(d => d.ImageFile, new { Type = "file" })
            @Html.ValidationMessage("Imagen", new { @class = "text-danger" })
            <br />
            <div style="text-align:right">
                <input type="submit" class="btn btn-success" value="Agregar" />
            </div>
        }

    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SistemaDeGestion/SistemaDeGestion/Views/Flyer/Delete.cshtml
@model SistemaDeGestion.Models.DeleteFlyerModel

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>
    ¿Estás seguro de que quieres eliminar esto?
</h3>
<div>
    <h4>FlyerModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Imagen))
            {
                <img src="@Url.Content(Model.Imagen)" alt="Image" style="width:200px; height:200px; max-width:100%; height:auto;" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm("Delete","Flyer", FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SistemaDeGestion/SistemaDeGestion/Views/Flyer/Edit.cshtml
@model SistemaDeGestion.Models.EditImageFlyer

@{
    ViewBag.Title = "Editar Flyer";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-lg-12">

        @using (Html.BeginForm("Edit", "Flyer", FormMethod.Post, new { role = "form", @class = "", enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(d => d.Id)
            @Html.ValidationMessage("Error", new { @class = "text-danger" })

            @Html.LabelFor(d => d.Name)
            @Html.TextBoxFor(d => d.Name, new { @class = "form-control" })
            @Html.ValidationMessage("Nombre", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.Description)
            @Html.TextBoxFor(d => d.Description, new { @class = "form-control" })
            @Html.ValidationMessage("Description", new { @class = "text-danger" })
            <br />

            @Html.LabelFor(d => d.ImageFile)
            @Html.TextBoxFor(d => d.ImageFile, new { Type = "file" })
            <br />

            <div style="text-align:right">
                <input type="submit" class="btn btn-success" value="Aceptar" />
            </div>
        }

    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

SistemaDeGestion/SistemaDeGestion/Views/Flyer/Index.cshtml
@model List<SistemaDeGestion.Models.FlyerModel>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<p>
    <button onclick="document.location.href='@Url.Content("~/Flyer/Create")'" class="btn btn-success">
        Agregar
        <span class="glyphicon glyphicon-plus"></span>
    </button>
</p>

<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Description</th>
                <th>Imagen</th>
            </tr>

            @foreach (var oElement in Model)
            {
        <tr>
            <td>@oElement.Id</td>
            <td>@oElement.Name</td>
            <td>@oElement.Description</td>
            <td>
                @if (!string.IsNullOrEmpty(oElement.Imagen))
                {
                    <img src="@Url.Content(oElement.Imagen)" alt="Image" style="width:100px; height:150px; max-width:100%; height:auto;" />
                }
            </td>
            <td>
                <button onclick="document.location.href='@Url.Content("~/Flyer/Edit/"+oElement.Id)'" type="button" class="btn btn-default">
                    Editar
                    <span class="glyphicon glyphicon-pencil"></span>
                </button>
                <button onclick="document.location.href='@Url.Content("~/Flyer/Delete/"+oElement.Id)'" type="button" class="btn btn-danger">
                    Eliminar
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </td>
        </tr>
            }
        </table>
    </div>
</div>